Repository radon-project/radon, pull requests merged in 2024-06, with the labels that each got.

#155 Explicit variable declaration
  core/errors.py
  core/interpreter.py
  core/parser.py
  core/tokens.py
  stdlib/argparser.rn
  stdlib/array.rn
  stdlib/math.rn
  stdlib/radiation.rn
  stdlib/string.rn
  stdlib/system.rn
  stdlib/universe.rn
  tests/classes.rn
  tests/closures.rn
  tests/empty-blocks.rn
  tests/files.rn
  tests/functions.rn
  tests/hashmap.rn
  tests/help.rn
  tests/in-op.rn
  tests/incdec.rn
  tests/incdec.rn.json
  tests/json_class.rn
  tests/loops.rn
  tests/modules2.rn
  tests/pyapi_advanced.rn
  tests/radiation-modules.rn
  tests/requests-tests.rn
  tests/scope-bug.rn
  tests/slice-bruteforce.rn
  tests/slicings.rn
  tests/string_class.rn
  tests/switch-case.rn
  tests/thicc-hm.rn
Labels: feature

#158 feat: added `io` stdlib support.
  core/errors.py
  core/tokens.py
  examples/files.rn
  examples/io-test.rn
  stdlib/io.rn
Labels: enhancement, feature

#159 Fix variadic arguments bug
  core/builtin_funcs.py
  core/datatypes.py
  core/interpreter.py
  core/nodes.py
  core/parser.py
  core/tokens.py
  tests/va_bug.rn
  tests/va_bug.rn.json
Labels: patch

#161 fix: `io.Output.write` method.
  examples/io-test.rn
  stdlib/io.rn
Labels: patch

#165 feat: added new stdlib `os`.
  core/datatypes.py
  core/tokens.py
  examples/os_examples.rn
  stdlib/os.rn
Labels: feature
