Repository radon-project/radon, pull requests merged in 2024-05, with the labels that each got.

#130 Renamed `include` to `import`
  Makefile
  core/interpreter.py
  core/nodes.py
  core/parser.py
  core/tokens.py
  examples/args_test.rn
  examples/arrays.rn
  examples/colors_test.rn
  examples/import_test.rn
  examples/operators-bug.rn
  tests/universe.rn
Labels: enhancement, syntax, core, proposal

#140 Added builtin radiation tracebacks.
  core/errors.py
  core/tokens.py
  examples/radiation-raise.rn
  radon.py
  stdlib/radiation.rn
  test.py
  tests/radiation-modules.rn
  tests/radiation-modules.rn.json
  tests/raise.rn.json
  tests/raise2.rn.json
  tests/raise3.rn.json
Labels: enhancement

#142 Implement `as` keyword for `import` statements
  core/interpreter.py
  core/nodes.py
  core/parser.py
  tests/modules2.rn
Labels: enhancement, proposal

#141 Correctly fetch system info in `system.rn`
  stdlib/system.rn
Labels: enhancement, stdlib

#146 Fix `Runtime Error: No cases matched` issue
  core/interpreter.py
  tests/modules2.rn.json
  tests/switch-case.rn
  tests/switch-case.rn.json
Labels: patch
